# Generated by Django 3.0.5 on 2020-04-16 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bible', '0002_biblecomment_biblenotebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bible',
            name='bible_book',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='bible_chapter',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='bible',
            name='user',
        ),
        migrations.CreateModel(
            name='BibleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bible_book', models.CharField(max_length=50)),
                ('bible_chapter', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
